src/Acts/CamdramBundle/Entity/Event.php
<?php

namespace Acts\CamdramBundle\Entity;

use Acts\CamdramApiBundle\Entity\ArrayEntity;
use Acts\CamdramSecurityBundle\Security\OwnableInterface;
use Acts\DiaryBundle\Model\EventInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use Gedmo\Mapping\Annotation as Gedmo;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * Event
 *
 * @Gedmo\Loggable
 * @ORM\Table(name="acts_events",
 *      indexes={@ORM\Index(name="idx_event_fulltext", columns={"text"}, flags={"fulltext"})})
 * @ORM\Entity
 */
class Event extends BaseEntity implements EventInterface, OwnableInterface
{
    use MultipleSocsTrait;

    /**
     * @var string
     *
     * @Assert\NotBlank()
     * @ORM\Column(name="text", type="string", length=255, nullable=false)
     * @Serializer\Exclude(if="object.getLinkId() != null")
     * @Serializer\XmlElement(cdata=false)
     */
    private $name;

    /**
     * This property holds the CLOCK TIME that the event ends regardless of time zones etc.
     *
     * @var \DateTime
     * @Assert\NotBlank()
     * @ORM\Column(name="endtime", type="time", nullable=false)
     * @Serializer\Exclude
     * @Serializer\XmlElement(cdata=false)
     */
    private $end_time;

    /**
     * This property holds the UTC date and time that the event starts.
     *
     * @var \DateTime
     * @Assert\NotBlank()
     * @ORM\Column(name="start_at", type="datetime", nullable=false)
     * @Serializer\XmlElement(cdata=false)
     */
    private $start_at;

    /**
     * @var string
     *
     * @Assert\NotBlank()
     * @ORM\Column(name="description", type="text", nullable=false)
     * @Serializer\Exclude(if="object.getLinkId() != null")
     * @Serializer\XmlElement(cdata=false)
     */
    private $description;

    /**
     * @var ?Event
     *
     * @ORM\ManyToOne(targetEntity="Event", inversedBy="linked_dates")
     * @ORM\OrderBy({"start_at" = "ASC"})
     * @ORM\JoinColumns({
     *   @ORM\JoinColumn(name="linkid", referencedColumnName="id", onDelete="CASCADE")
     * })
     * @Serializer\SerializedName("root_event")
     */
    private $link_id;

    /**
     * @Assert\Valid(traverse=true)
     * @ORM\OneToMany(targetEntity="Event", mappedBy="link_id", cascade={"persist", "remove"})
     * @Serializer\Exclude
     */
    private $linked_dates;

    /**
     * @var ?ArrayCollection<Event>
     */
    private $deleted_dates;

    /**
     * All the registered scieties involved with this show.
     * @ORM\ManyToMany(targetEntity="Society", inversedBy="events")
     * @ORM\JoinTable(name="acts_event_soc_link")
     * @Serializer\Exclude
     */
    private $societies;

    /**
     * Should be in #f21343 notation, if it isn't the form is broken. (It uses JS to enforce the notation.)
     * @var ?string
     * @Assert\Regex("/^#[0-9A-Fa-f]{6}$/",
     *     message="The provided colour must be in six-digit hex notation. If this isn't working leave it blank and contact support.")
     * @ORM\Column(name="colour", type="string", length=7, nullable=true)
     * @Serializer\Exclude(if="object.getLinkId() != null")
     * @Serializer\XmlElement(cdata=false)
     */
    private $theme_color;

    /**
     * @var ?Image
     *
     * @ORM\ManyToOne(targetEntity="Image")
     * @Gedmo\Versioned
     * @Serializer\Exclude(if="object.getLinkId() != null")
     */
    private $image;

    public function __construct()
    {
        $this->deleted_dates = new ArrayCollection();
        $this->linked_dates = new ArrayCollection();
        $this->societies    = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @param \DateTime $endTime
     */
    public function setEndTime($endTime): self
    {
        $this->end_time = $endTime;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getEndTime()
    {
        return $this->end_time;
    }

    /**
     * @param \DateTime $startAt
     */
    public function setStartAt($startAt): self
    {
        $this->start_at = $startAt;

        return $this;
    }

    /**
     * @return \DateTime
     */
    public function getStartAt()
    {
        return $this->start_at;
    }

    /**
     * @param string $description
     */
    public function setDescription($description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return string
     */
    public function getDescription()
    {
        return ($this->getLinkId() ?: $this)->description;
    }

    public function setLinkId(?Event $linkId): self
    {
        $this->link_id = $linkId;

        return $this;
    }

    /**
     * @return ?Event
     */
    public function getLinkId()
    {
        return $this->link_id;
    }

    /** @return iterable<Event> */
    public function getLinkedDates()
    {
        return $this->linked_dates;
    }

    public function addLinkedDate(Event $evt): self
    {
        $this->linked_dates->add($evt);
        $evt->setLinkId($this);
        return $this;
    }

    public function removeLinkedDate(Event $evt): self
    {
        $this->linked_dates->removeElement($evt);
        $this->getDeletedDates()->add($evt);
        return $this;
    }

    /** @return ArrayCollection<Event> */
    public function getDeletedDates(): ArrayCollection
    {
        if (!$this->deleted_dates) $this->deleted_dates = new ArrayCollection();
        return $this->deleted_dates;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;
        return $this;
    }

    public function getName(): ?string
    {
        return ($this->getLinkId() ?: $this)->name;
    }

    /**
     * Required for BaseEntity, actually returns the ID.
     */
    public function getSlug(): string
    {
        return "{$this->getId()}";
    }

    public static function getAceType(): string
    {
        return "event";
    }

    public function getEntityType(): string
    {
        return "event";
    }

    public function getTimes(): array
    {
        $dateList = [];
        $dateList[] = [$this->getStartAt(), $this->getEndTime()];

        foreach ($this->linked_dates as $linked) {
            $dateList[] = [$linked->getStartAt(), $linked->getEndTime()];
        }

        usort($dateList, function ($a, $b) { return $a <=> $b; });
        return $dateList;
    }

    public function getThemeColor()
    {
        return $this->theme_color;
    }

    public function setThemeColor(?string $color): self
    {
        $this->theme_color = $color;
        return $this;
    }

    public function setImage(?Image $image): self
    {
        $this->image = $image;
        return $this;
    }

    public function getImage()
    {
        return $this->image;
    }

    /**
     * @Serializer\Exclude(if="object.getLinkId() != null")
     * @Serializer\SerializedName("dates")
     * @Serializer\VirtualProperty()
     * @Serializer\XmlList(entry="date")
     */
    public function getSubeventsForAPI(): array
    {
        $evts = array_merge([$this], $this->linked_dates->toArray());
        $out = [];
        foreach ($evts as $date) {
            $out[] = new ArrayEntity([
                'start_at' => $date->getStartAt(),
                'end_at' => $date->getEndAt(),
                'id' => $date->getId(),
            ]);
        }
        return $out;
    }

    public function shouldSerializeSocieties(): bool
    {
        return $this->link_id == null;
    }

    // EventInterface

    /**
     * Returns the DateTime that this event ends calculated from the start_at
     * and end_time fields.
     * @Serializer\VirtualProperty()
     * @Serializer\XmlElement(cdata=false)
     */
    public function getEndAt(): \DateTime
    {
        $endtime = explode(':', $this->getEndTime()->format('H:i:s'));
        $enddatetime = clone $this->getStartAt();
        $enddatetime->setTimezone(new \DateTimeZone('Europe/London'));
        $enddatetime->setTime(...array_map('intval', $endtime));
        if ($enddatetime < $this->getStartAt()) $enddatetime->modify('+1 day');
        return $enddatetime;
    }

    public function getRepeatUntil()
    {
        return $this->getStartAt();
    }

    public function getUpdatedAt()
    {
        return new \DateTime('1970-01-01 01:00');
    }

    public function getVenue()
    {
        return null;
    }

    public function getVenueName()
    {
        return '';
    }
}

src/Acts/CamdramBundle/Entity/Society.php
<?php

namespace Acts\CamdramBundle\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use JMS\Serializer\Annotation as Serializer;
use Symfony\Component\Validator\Constraints as Assert;
use Acts\CamdramApiBundle\Configuration\Annotation as Api;

/**
 * Society
 *
 * @ORM\Table(name="acts_societies", uniqueConstraints={@ORM\UniqueConstraint(name="org_slugs",columns={"slug"})},
 *      indexes={@ORM\Index(name="idx_society_fulltext", columns={"name", "shortname", "slug"}, flags={"fulltext"})})
 * @ORM\Entity()
 * @Gedmo\Loggable
 * @Serializer\ExclusionPolicy("all")
 * @Serializer\XmlRoot("society")
 */
class Society extends Organisation
{
    /**
     * @ORM\ManyToMany(targetEntity="Show", mappedBy="societies")
     * @Api\Link(route="acts_camdram_society_getshows", params={"identifier": "object.getSlug()"})
     */
    private $shows;

    /**
     * @ORM\ManyToMany(targetEntity="Event", mappedBy="societies")
     */
    private $events;

    private $entity_type = 'society';

    /**
     * Should be in #f21343 notation, if it isn't the form is broken. (It uses JS to enforce the notation.)
     * @var ?string
     * @Assert\Regex("/^#[0-9A-Fa-f]{6}$/",
     *     message="The provided colour must be in six-digit hex notation. If this isn't working leave it blank and contact support.")
     * @ORM\Column(name="colour", type="string", length=7, nullable=true)
     * @Serializer\Expose
     * @Serializer\Type("string")
     */
    private $theme_color;

    /**
     * @var string
     *
     * @ORM\Column(name="name", type="string", length=255, nullable=false)
     * @Assert\NotBlank()
     * @Serializer\Expose
     * @Gedmo\Versioned
     * @Serializer\XmlElement(cdata=false)
     */
    private $name;

    /**
     * @var ?string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     * @Serializer\Expose
     * @Gedmo\Versioned
     */
    private $description;

    /**
     * @var ?Image
     *
     * @ORM\ManyToOne(targetEntity="Image")
     * @Gedmo\Versioned
     * @Serializer\Expose()
     */
    private $image;

    /**
     * @var ?string
     *
     * @ORM\Column(name="facebook_id", type="string", length=50, nullable=true)
     * @Serializer\Expose
     * @Gedmo\Versioned
     * @Serializer\XmlElement(cdata=false)
     */
    private $facebook_id;

    /**
     * @var ?string
     *
     * @ORM\Column(name="twitter_id", type="string", length=50, nullable=true)
     * @Serializer\Expose
     * @Gedmo\Versioned
     * @Serializer\XmlElement(cdata=false)
     */
    private $twitter_id;

    /**
     * @var ?string
     *
     * @ORM\Column(name="shortname", type="string", length=100, nullable=true)
     * @Serializer\Expose
     * @Gedmo\Versioned
     * @Serializer\XmlElement(cdata=false)
     */
    private $short_name;

    /**
     * @var ?string
     *
     * @ORM\Column(name="college", type="string", length=100, nullable=true)
     * @Serializer\Expose
     * @Gedmo\Versioned
     * @Serializer\XmlElement(cdata=false)
     */
    private $college;

    /**
     * @var ?string
     *
     * @ORM\Column(name="logourl", type="string", length=255, nullable=true)
     */
    private $logo_url;

    /**
     * @Gedmo\Slug(handlers={
     *      @Gedmo\SlugHandler(class="Acts\CamdramBundle\Service\SlugHandler", options={})
     * }, fields={"name"})
     * @ORM\Column(name="slug", type="string", length=128, nullable=false)
     * @Serializer\Expose
     * @Serializer\XmlElement(cdata=false)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity="Advert", mappedBy="society")
     */
    private $adverts;

    public function setShortName(?string $shortName): self
    {
        $this->short_name = $shortName;
        return $this;
    }

    public function getShortName(): ?string
    {
        return $this->short_name;
    }

    public function setCollege(?string $college): self
    {
        $this->college = $college;
        return $this;
    }

    public function getCollege(): ?string
    {
        return $this->college;
    }

    public function setLogoUrl(?string $logoUrl): self
    {
        $this->logo_url = $logoUrl;

        return $this;
    }

    public function getLogoUrl(): ?string
    {
        return $this->logo_url;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function setName(?string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    /**
     * Set description
     *
     * @param string $description
     *
     * @return Organisation
     */
    public function setDescription($description)
    {
        $this->description = $description;

        return $this;
    }

    /**
     * Get description
     *
     * @return string
     */
    public function getDescription()
    {
        return $this->description;
    }

    /**
     * Set facebook_id
     *
     * @param string $facebookId
     *
     * @return Organisation
     */
    public function setFacebookId($facebookId)
    {
        $this->facebook_id = $facebookId;

        return $this;
    }

    /**
     * Get facebook_id
     *
     * @return string
     */
    public function getFacebookId()
    {
        return $this->facebook_id;
    }

    public function setTwitterId(?string $twitterId): self
    {
        $this->twitter_id = $twitterId;

        return $this;
    }

    public function getTwitterId(): ?string
    {
        return $this->twitter_id;
    }

    /**
     * Set image
     *
     * @param Image $image
     *
     * @return Organisation
     */
    public function setImage(Image $image = null)
    {
        $this->image = $image;

        return $this;
    }

    /**
     * Get image
     *
     * @return Image
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Set slug
     *
     * @param string $slug
     *
     * @return Organisation
     */
    public function setSlug($slug)
    {
        $this->slug = $slug;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    /**
     * Constructor
     */
    public function __construct()
    {
        $this->adverts = new \Doctrine\Common\Collections\ArrayCollection();
        $this->events = new \Doctrine\Common\Collections\ArrayCollection();
        $this->shows = new \Doctrine\Common\Collections\ArrayCollection();
    }

    public static function getAceType() : string
    {
        return 'society';
    }

    public function getEntityType(): string
    {
        return $this->entity_type;
    }

    /**
     * Add shows
     *
     * @param \Acts\CamdramBundle\Entity\Show $shows
     *
     * @return Society
     */
    public function addShow(\Acts\CamdramBundle\Entity\Show $shows)
    {
        $this->shows[] = $shows;

        return $this;
    }

    /**
     * Remove shows
     *
     * @param \Acts\CamdramBundle\Entity\Show $shows
     */
    public function removeShow(\Acts\CamdramBundle\Entity\Show $shows)
    {
        $this->shows->removeElement($shows);
    }

    /**
     * Get shows
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getShows()
    {
        return $this->shows;
    }

    public function getIndexDate()
    {
        return null;
    }

    public function getOrganisationType()
    {
        return 'society';
    }

    public function setThemeColor(?string $theme_color): self
    {
        $this->theme_color = $theme_color;
        return $this;
    }

    public function getThemeColor(): ?string
    {
        return $this->theme_color;
    }

    /**
     * @return Collection|Advert[]
     */
    public function getAdverts(): Collection
    {
        return $this->adverts;
    }

    public function addAdvert(Advert $advert): self
    {
        if (!$this->adverts->contains($advert)) {
            $this->adverts[] = $advert;
            $advert->setSociety($this);
        }

        return $this;
    }

    public function removeAdvert(Advert $advert): self
    {
        if ($this->adverts->contains($advert)) {
            $this->adverts->removeElement($advert);
            // set the owning side to null (unless already changed)
            if ($advert->getSociety() === $this) {
                $advert->setSociety(null);
            }
        }

        return $this;
    }
}

templates/event/admin-panel.html.twig
{% if is_granted('EDIT', event) %}
<div class="admin-panel">
    <h6 class="split-header">
        <span>Event Administration: {{ link_entity(event) }}</span>
        <span>ID: {{ event.id}}</span></h6>
    <ul role="menubar">
        {{ include('navigation/nav-item.html.twig', {item: {id: 'edit_event', path: path('acts_camdram_event_edit',{identifier:event.slug}), icon: 'pencil', text: 'Edit this event'} }) }}
        {% if is_granted('DELETE', event) %}
            {{ include('navigation/form-item.html.twig', {item: {id: 'delete_event',
                path: path('acts_camdram_event_delete', {identifier:event.slug}), method: 'DELETE', text: 'Delete this event', icon: 'eraser'},
                destructive: {title: "Are you sure you want to delete the event “" ~ event.name ~ "”?", text: "This is a permanent action that cannot be undone" }
                }) }}
        {% endif %}
        {{ include('navigation/nav-item.html.twig', {item: {
            id: 'edit_admin',
            path: path('edit_entity_admin',{type: 'events', identifier:event.slug}),
            icon: 'pencil', text: "Edit the event's admins"} }) }}
    </ul>

    <p>
    {% if admins is not empty %}
        The following people and/or groups can edit this event:
    {% endif %}
    {% for admin in admins %}
        {%- if admin.person is defined %}
            {%- if admin.person -%}
                <a href="{{ path('get_person', {identifier: admin.person.slug}) }}">{{ admin.name }}</a>
            {%- else -%}
                {{ admin.name }}
            {%- endif -%}
        {%- elseif admin.organisationType == 'society' %}
            <a href="{{ path('get_society', {identifier: admin.slug}) }}">{{ admin.name }}</a>
        {%- elseif admin.organisationType == 'venue' %}
            <a href="{{ path('get_venue', {identifier: admin.slug}) }}">{{ admin.name }}</a>
        {%- endif %}
        {{- not loop.last ? ',' }}
    {% endfor %}
    </p>
{% if pending_admins is not empty %}
    <p>
        The following people will be admins, pending creating an account:
        {% for pending in pending_admins %}
            {{ pending.email }}
            {{- not loop.last ? ',' }}
        {% endfor %}
        </p>
    {% endif %}
</div>
{% endif %}

templates/event/by-society.html.twig
{% set current_navigation_id = 'events' %}
{% extends 'layout.html.twig' %}

{% block title %}Events from {{society.name}} - Camdram{% endblock %}

{% block body %}
<div class="split-header">
    <h3>Events from {{ link_entity(society) }}</h3>
    <a href="{{ path('acts_camdram_event_new') }}"><i class="fa fa-edit"></i> Add a workshop or talk...</a>
</div>

<p><a href="{{ path('get_events') }}"><i class="fa fa-chevron-left"></i> View all upcoming events</a></p>

{% include 'paginator.html.twig' %}
<ul class="large-block-list">
{%- for event in paginator -%}
    <li>
        <div class="panel">
            <h5>{{ link_entity(event) }}</h5>
            <ul class="event-dates-section">
            {%- for date in event.times -%}
                <li>{{ date[0]|date }}–{{ date[1]|date('H:i', false) }}
            {%- endfor -%}</ul>

            <p>{{ event.description | camdram_markdown | truncateHTML(200) }}</p>
        </div>
    </li>
{%- endfor -%}
</ul>
{% include 'paginator.html.twig' %}
{% endblock %}

templates/event/edit.html.twig
{% extends 'layout.html.twig' %}

{% set current_navigation_id = 'events' %}
{% block title %}Event - {{ form.vars.value.name }} - Edit{% endblock %}

{% block body %}

{{ render(admin_panel(form.vars.value)) }}

<h3>Edit Event</h3>
{{ form_start(form, {'action': path("acts_camdram_event_put", {identifier: form.vars.value.id} )}) }}

{% include 'event/form.html.twig' %}

<div class="text-right">
    <input type="submit" value="Save" class="button"/>
</div>

{{ form_end(form) }}

{% endblock %}

templates/event/historic.html.twig
{% set current_navigation_id = 'events' %}
{% extends 'layout.html.twig' %}

{% block title %}Past events - Camdram{% endblock %}

{% block body %}
<div class="split-header">
    <h2>Past events</h2>
    <a href="{{ path('acts_camdram_event_new') }}"><i class="fa fa-edit"></i> Add a workshop or talk...</a>
</div>

<p><a href="{{ path('get_events') }}"><i class="fa fa-chevron-left"></i> View upcoming events</a></p>

{% include 'paginator.html.twig' %}
<ul class="large-block-list">
{%- for event in resultset.data -%}
    <li>
        <div class="panel">
            <h5>{{ link_entity(event) }}</h5>
            <ul class="event-dates-section">
            {%- for date in event.times -%}
                <li>{{ date[0]|date }}–{{ date[1]|date('H:i', false) }}
            {%- endfor -%}</ul>

            <p>{{ event.description | camdram_markdown | truncateHTML(200) }}</p>
        </div>
    </li>
{%- endfor -%}
</ul>
{% include 'paginator.html.twig' %}
{% endblock %}

templates/event/index.html.twig
{% extends 'layout.html.twig' %}

{% set current_navigation_id = 'events' %}
{% block title %}Events{% endblock %}

{% block body %}

<div class="split-header">
    <h2>Upcoming events</h2>
    <a href="{{ path('acts_camdram_event_new') }}"><i class="fa fa-edit"></i> Add a workshop or talk...</a>
</div>
{%- if resultset.data is not empty -%}
    <ul class="large-block-list">
    {%- for event in resultset.data -%}
        <li>
            <div class="panel">
                <h5>{{ link_entity(event) }}</h5>
                <ul class="event-dates-section">
                {%- for date in event.times -%}
                    <li>{{ date[0]|date }}–{{ date[1]|date('H:i', false) }}
                {%- endfor -%}</ul>

                <p>{{ event.description | camdram_markdown | truncateHTML(200) }}</p>
            </div>
        </li>
    {%- endfor -%}
    </ul>
{%- else -%}
    <p>There are no upcoming events at the moment. If you have a workshop or other event coming up you can advertise it here.</p>
{%- endif -%}

{%- include 'paginator.html.twig' -%}

<p><a href="{{ path('acts_camdram_event_historic') }}">View past events <i class="fa fa-chevron-right"></i></a></p>

{% endblock %}

templates/event/new.html.twig
{% extends 'layout.html.twig' %}

{% set current_navigation_id = 'events' %}
{% block title %}New event - Camdram{% endblock %}

{% block body %}

<h3>New Event</h3>

<div class="panel">
    <p>Use this form to advertise workshops, talks, and other events.
       For shows, films and auditions,
       <a href="{{ path('acts_camdram_show_new') }}">create a show entry instead</a>.</p>
</div>

{{ form_start(form, {'action': path("acts_camdram_event_post")}) }}

{% include 'event/form.html.twig' %}

<div class="text-right">
    <input type="submit" value="Create" class="button"/>
</div>

{{ form_end(form) }}

{% endblock %}

templates/event/show.html.twig
{% extends 'layout.html.twig' %}

{% set current_navigation_id = 'events' %}
{% if event.themeColor %}
    {% set colors = wcag_colors(event.themeColor) %}
    {% set body_attribs_raw = ' style="--custom-color: '  ~ colors['raw'] ~
                                    '; --color-text: ' ~ colors['smalltext'] ~ ';"' ~
                              ' class="entity-has-theme-color"' %}
{% endif %}
{% block title %}{{ event.name }} – Camdram{% endblock %}

{# Facebook open graph markup #}
{% block opengraph %}
    <meta property="og:url" content="{{ url('get_event', {identifier: event.id}) }}" />
    <meta property="og:title" content="{{ event.name }}" />
    <meta property="og:description" content="{{ event.description | strip_camdram_markdown | strip_new_lines | truncate(500) }}" />
    {% if event.image %}
        <meta property="og:image" content="{{ event.image.filename | imagine_filter('preview') }}" />
    {% else %}
        {# Maybe put a stock camdram image here? #}
    {% endif %}
{% endblock %}

{% block body %}

{% if is_granted('EDIT', event) %}
{{ render(admin_panel(event)) }}
{% endif %}

<div class="row panel">
    <meta itemprop="name" content="{{ event.name }}"/>

    <h2 itemprop="name">{{ event.name }}</h2>

    {%- for soc in event.prettysocdata -%}
        {{- loop.first ? '<p style="font-weight: bold; color: #333">From ' | raw -}}
        <span itemprop="organizer" itemscope="" itemtype="http://schema.org/TheaterGroup">
        {%- if soc.id is defined -%}
            <a href="{{ path('get_society', {identifier: soc.slug}) }}" itemprop="url"><span itemprop="name">{{ soc.name }}</span></a>
        {%- else -%}
            <span itemprop="name" content="{{ soc.name }}">{{ soc.name }}</span>
        {%- endif -%}
        </span>
        {{- list_sep_verb(loop) -}}
        {{- loop.last ? '.</p>' | raw -}}
    {%- endfor -%}

    <ul class="event-dates-section">
    {%- for date in event.times -%}
        <li>{{ date[0]|date }}–{{ date[1]|date('H:i', false) }}
    {%- endfor -%}</ul>

    {# Display event image #}
    {%- if event.image -%}
        <div class="entity-image-container">
            <a itemprop="image" href="{{ event.image.filename | imagine_filter('preview') }}" class="show-image-modal"><img src="{{ event.image.filename | imagine_filter('thumbnail') }}" /></a>
            {%- if is_granted('EDIT', event) and is_granted("IS_AUTHENTICATED_FULLY") -%}
                <ul class="inline-list">
                {{ include('navigation/form-item.html.twig', {item: {id: 'delete_event_image',
                    path: path('delete_event_image', {identifier:event.slug}), method: 'DELETE', text: 'Remove image', icon: 'eraser'},
                    destructive: {title: "Are you sure you want to delete the image for “" ~ event.name ~ "”?" }
                    }) }}
                </ul>
            {%- endif -%}
        </div>

        {# Show prompt to upload image #}
    {%- elseif is_granted('EDIT', event) and is_granted("IS_AUTHENTICATED_FULLY") -%}
        <div class="entity-image-container">
            <form action="{{ oneup_uploader_endpoint('images') }}" id="image_upload" class="dropzone">
                <input type="hidden" name="identifier" value="{{ event.slug }}"/>
                <input type="hidden" name="type" value="event"/>
            </form>
        </div>
    {%- endif -%}
    <div class="entity-body-text">
        {{ event.description | camdram_markdown }}
    </div>
</div>

{% endblock %}