src/Acts/CamdramBundle/Entity/Show.php
<?php

namespace Acts\CamdramBundle\Entity;

use Acts\CamdramSecurityBundle\Security\OwnableInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Symfony\Component\Validator\Constraints as Assert;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Criteria;
use Gedmo\Mapping\Annotation as Gedmo;
use JMS\Serializer\Annotation as Serializer;
use Acts\CamdramSecurityBundle\Entity\User;
use Acts\CamdramApiBundle\Configuration\Annotation as Api;

/**
 * Show
 *
 * @ORM\Table(name="acts_shows", uniqueConstraints={@ORM\UniqueConstraint(name="show_slugs",columns={"slug"})},
 *      indexes={@ORM\Index(name="idx_show_fulltext", columns={"title", "slug"}, flags={"fulltext"})})
 * @ORM\Entity(repositoryClass="Acts\CamdramBundle\Entity\ShowRepository")
 * @ORM\EntityListeners({"Acts\CamdramBundle\EventListener\ShowListener"})
 * @Serializer\ExclusionPolicy("all")
 * @Serializer\XmlRoot("show")
 * @Gedmo\Loggable
 * @Api\Feed(name="Camdram - Shows", titleField="name",
 *   description="Amateur shows produced in Cambridge",
 *   template="show/rss.html.twig")
 * @Api\Link(route="get_show", params={"identifier": "object.getSlug()"})
 */
class Show extends BaseEntity implements OwnableInterface
{
    use MultipleSocsTrait;

    /**
     * The show's name
     *
     * @var string
     *
     * @ORM\Column(name="title", type="string", length=255, nullable=false)
     * @Assert\NotBlank()
     * @Gedmo\Versioned
     * @Serializer\Expose()
     * @Serializer\Type("string")
     * @Serializer\XmlElement(cdata=false)
     */
    private $name;

    /**
     * A description of the show
     *
     * @var ?string
     *
     * @ORM\Column(name="description", type="text", nullable=true)
     * @Gedmo\Versioned
     * @Serializer\Expose()
     * @Serializer\Type("string")
     */
    private $description;

    /**
     * A content warning.
     *
     * @var ?string
     *
     * @ORM\Column(name="content_warning", type="text", nullable=true)
     * @Gedmo\Versioned
     * @Serializer\Expose()
     * @Serializer\Type("string")
     */
    private $content_warning;

    /**
     * @var ?Image
     *
     * @ORM\ManyToOne(targetEntity="Image")
     * @Gedmo\Versioned
     * @Serializer\Expose()
     */
    private $image;

    /**
     * @var ?string
     *
     * @ORM\Column(name="facebook_id", type="string", length=50, nullable=true)
     * @Gedmo\Versioned
     */
    private $facebook_id;

    /**
     * @var ?string
     *
     * @ORM\Column(name="twitter_id", type="string", length=50, nullable=true)
     * @Gedmo\Versioned
     */
    private $twitter_id;

    /**
     * The 'slug' of the show (used to generate the URL)
     *
     * @Gedmo\Slug(handlers={
     *      @Gedmo\SlugHandler(class="Acts\CamdramBundle\Service\SlugHandler", options={
     *          @Gedmo\SlugHandlerOption(name="dateField", value="start_at"),
     *      })
     * }, fields={"name"})
     * @ORM\Column(name="slug", type="string", length=128, nullable=false)
     * @Serializer\Expose
     * @Serializer\Type("string")
     * @Serializer\XmlElement(cdata=false)
     */
    private $slug;

    /**
     * @var string
     *
     * @ORM\Column(name="dates", type="string", length=255, nullable=false)
     */
    private $dates = '';

    /**
     * The show's author (free text string, which may be blank or contain one or more author names)
     *
     * @var ?string
     *
     * @ORM\Column(name="author", type="string", length=255, nullable=true)
     * @Gedmo\Versioned
     * @Serializer\Expose()
     * @Serializer\Type("string")
     * @Serializer\XmlElement(cdata=false)
     */
    private $author;

    /**
     * A string representing the ticket price options
     *
     * @var ?string
     *
     * @ORM\Column(name="prices", type="string", length=255, nullable=true)
     * @Gedmo\Versioned
     * @Serializer\Expose()
     * @Serializer\Type("string")
     * @Serializer\XmlElement(cdata=false)
     */
    private $prices = '';

    /**
     * @var ?string
     *
     * @ORM\Column(name="photourl", type="text", nullable=true)
     */
    private $photo_url = '';

    /**
     * All the registered scieties involved with this show.
     * @ORM\ManyToMany(targetEntity="Society", inversedBy="shows")
     * @ORM\JoinTable(name="acts_show_soc_link")
     */
    private $societies;

    /**
     * @var bool
     *
     * @ORM\Column(name="authorised", type="boolean")
     * @Gedmo\Versioned
     */
    private $authorised = false;

    /**
     * The show's genre (takes one of several predefined values)
     *
     * @var string
     *
     * @ORM\Column(name="category", type="string", length=255, nullable=false)
     * @Assert\NotBlank()
     * @Serializer\Expose
     * @Serializer\Type("string")
     * @Serializer\XmlElement(cdata=false)
     */
    private $category;

    /**
     * @var \DateTime
     *
     * @ORM\Column(name="timestamp", type="datetime", nullable=false)
     */
    private $timestamp;

    /**
     * @ORM\OneToMany(targetEntity="Advert", mappedBy="show", cascade={"all"}, orphanRemoval=true)
     */
    private $adverts;

    /**
     * @ORM\OneToMany(targetEntity="Role", mappedBy="show")
     * @ORM\OrderBy({"type" = "ASC", "order" = "ASC"})
     * @Api\Link(route="get_show_roles", params={"identifier": "object.getSlug()"})
     */
    private $roles;

    /**
     * @Assert\Valid(traverse=true)
     * @ORM\OneToMany(targetEntity="Performance", mappedBy="show", cascade={"persist", "remove"}, orphanRemoval=true)
     * @ORM\OrderBy({"start_at" = "ASC"})
     * @Serializer\Expose()
     * @Serializer\XmlList(entry = "performance")
     */
    private $performances;

    /**
     * @var ?string
     * @ORM\Column(name="facebookurl", type="string", length=2083, nullable=true)
     */
    private $facebook_url;
    /**
     * @var ?string
     * @ORM\Column(name="otherurl", type="string", length=2083, nullable=true)
     */
    private $other_url;

    /**
     * Should be in #f21343 notation, if it isn't the form is broken. (It uses JS to enforce the notation.)
     * @var ?string
     * @Assert\Regex("/^#[0-9A-Fa-f]{6}$/",
     *     message="The provided colour must be in six-digit hex notation. If this isn't working leave it blank and contact support.")
     * @ORM\Column(name="colour", type="string", length=7, nullable=true)
     * @Serializer\Expose
     * @Serializer\Type("string")
     */
    private $theme_color;

    /**
     * A URL from which tickets for the show can be bought
     *
     * @var ?string
     * @Assert\Url()
     * @Gedmo\Versioned
     * @Serializer\Expose
     * @ORM\Column(name="onlinebookingurl", type="string", length=2083, nullable=true)
     * @Serializer\Expose
     * @Serializer\Type("string")
     * @Serializer\XmlElement(cdata=false)
     */
    private $online_booking_url;

    private $weeks = "";
    private $weekManager;

    private $entity_type = 'show';

    public function getEntityType(): string
    {
        return $this->entity_type;
    }

    /**
     * Set dates
     *
     * @param string $dates
     *
     * @return Show
     */
    public function setDates($dates)
    {
        $this->dates = $dates;
        return $this;
    }

    /**
     * Get dates
     *
     * @return string
     */
    public function getDates()
    {
        return $this->dates;
    }

    /**
     * Set author
     *
     * @param string $author
     *
     * @return Show
     */
    public function setAuthor($author)
    {
        $this->author = $author;

        return $this;
    }

    /**
     * Get author
     *
     * @return string
     */
    public function getAuthor()
    {
        return $this->author;
    }

    /**
     * Set prices
     *
     * @param string $prices
     *
     * @return Show
     */
    public function setPrices($prices)
    {
        $this->prices = $prices;

        return $this;
    }

    /**
     * Get prices
     *
     * @return ?string
     */
    public function getPrices()
    {
        return $this->prices;
    }

    /**
     * Set photo_url
     *
     * @param string $photoUrl
     *
     * @return Show
     */
    public function setPhotoUrl($photoUrl)
    {
        $this->photo_url = $photoUrl;

        return $this;
    }

    /**
     * Get photoUrl
     *
     * @return string
     */
    public function getPhotoUrl()
    {
        return $this->photo_url;
    }

    /**
     * Gets all registered venues referenced in this show's performances.
     */
    public function getVenues(): array
    {
        $venids = []; // Not returned, used to check for duplication.
        $venues = []; // Returned
        foreach ($this->performances as $p) {
            if (($v = $p->getVenue()) && !in_array($v->getId(), $venids, true)) {
                $venues[] = $v;
                $venids[] = $v->getId();
            }
        }
        return $venues;
    }

    /**
     * Returns a list of all venue names for this show.
     */
    public function getVenueNames(): array
    {
        return array_unique($this->performances->map(function($p) {
            return $p->getVenueName();
        })->toArray());
    }

    /**
     * Set category
     *
     * @param string $category
     *
     * @return Show
     */
    public function setCategory($category)
    {
        $this->category = $category;

        return $this;
    }

    /**
     * Get category
     *
     * @return string
     */
    public function getCategory()
    {
        return $this->category;
    }

    /**
     * Set timestamp
     *
     * @param \DateTime $timestamp
     *
     * @return Show
     */
    public function setTimestamp($timestamp)
    {
        $this->timestamp = $timestamp;

        return $this;
    }

    /**
     * Get timestamp
     *
     * @return \DateTime
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * Add roles
     *

src/Acts/CamdramSecurityBundle/Form/Type/PendingAccessType.php
<?php

namespace Acts\CamdramSecurityBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\HiddenType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;

/**
 * Class AceType
 *
 * The form that's presented when an Access Control Entry (ACE) is created
 */
class PendingAccessType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('email', EmailType::class)
            ->add('send', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults(array(
            'data_class' => 'Acts\CamdramSecurityBundle\Entity\PendingAccess'
        ));
    }
}

templates/pending_access/edit.html.twig
{% extends 'layout.html.twig' %}
{% block title %}Edit Admins{% endblock %}

{% block body %}

{{ render(admin_panel(entity)) }}

<p>
{% if entity.entityType == 'show' %}
    Admins are able to edit the details of a show, create adverts for production
    team vacancies, and edit the people listed who are involved in the show. These
    list show the current admins and the list of people who will be able to edit
    the show after they create an account on Camdram.
{% elseif entity.entityType == 'society' %}
    Society admins are able to edit the information listed on Camdram, authorise shows involving the society, and to open applications for new shows.
{% elseif entity.entityType == 'venue' %}
    Venue admins are able to edit the information listed on Camdram, authorise shows involving the venue, and to open applications for new shows.
{% endif %}
</p>

{% if requested_admins is not null %}
<h4>Admin Requests</h4>
{% if requested_admins is empty %}
<p>There are no requests to be an admin for this {{ entity.entityType }}.</p>
{% endif %}
{% for admin in requested_admins %}
    <div id="admin_{{ admin.id }}">
    <form action="{{ path('approve_show_admin', {identifier: entity.slug, uid: admin.id}) }}" method="post" class="inline-block">
        <input type="hidden" name="_method" value="PATCH" />
        <input type="hidden" name="_token" value="{{ csrf_token('approve_show_admin') }}" />
        <button title="Approve request." class="fa fa-fw fa-check-circle text-button"></button>
    </form>&ensp;
    <form action="{{ path('delete_entity_admin', {type: entity.entityType|plural(2), identifier: entity.slug, uid: admin.id}) }}" method="post" id="revoke_admin_form_{{ admin.id }}" class="inline-block">
        <input type="hidden" name="_method" value="DELETE" />
        <input type="hidden" name="_token" value="{{ csrf_token('delete_admin') }}" />
        <button title="Deny request." class="fa fa-fw fa-times-circle text-button"></button>
    </form>&ensp;
    {%- if admin.person is defined -%}
        {%- if admin.person -%}
            <a href="{{ path('get_person', {identifier: admin.person.slug}) }}">{{ admin.name }}</a>
        {%- else -%}
            {{ admin.name }}
        {%- endif -%}
    {%- endif -%}
    </div>
{% endfor %}
{% endif %}

<h4>Existing Admins</h4>
{% if admins is empty %}
<p>There are no admins specifically for this {{ entity.entityType }}.</p>
{% endif %}
{% for admin in admins %}
    <div id="admin_{{ admin.id }}">
        <form action="{{ path('delete_entity_admin', {type: entity.entityType|plural(2), identifier: entity.slug, uid: admin.id}) }}" method="post" id="revoke_admin_form_{{ admin.id }}" class="inline-block">
            <input type="hidden" name="_method" value="DELETE" />
            <input type="hidden" name="_token" value="{{ csrf_token('delete_admin') }}" />
            <button title="Revoke this admin." class="fa fa-fw fa-trash-o text-button"></button>
        </form>
    {% if admin.person is defined -%}
        {%- if admin.person -%}
            <a href="{{ path('get_person', {identifier: admin.person.slug}) }}">{{ admin.name }}</a>
        {%- else -%}
            {{ admin.name }}
        {%- endif -%}
    {%- endif -%}
    </div>
{% endfor %}

<h4>Pending Admins</h4>
{% if pending_admins is empty %}
<p>There are no pending admins for this {{ entity.entityType }}.</p>
{% endif %}
{% for pending in pending_admins %}
    <div id="pending_{{ pending.id }}">
    <form action="{{ path('delete_pending_admin', {type: entity.entityType|plural(2), identifier: entity.slug, uid: pending.id}) }}" method="post" id="revoke_pending_admin_form_{{ pending.id }}" class="inline-block">
        <input type="hidden" name="_method" value="DELETE" />
        <input type="hidden" name="_token" value="{{ csrf_token('delete_pending_admin') }}" />
        <button title="Revoke this pending admin." class="fa fa-fw fa-trash-o text-button"></button>
    </form>

    {{ pending.email }}
    </div>
{% endfor %}
<br/>
<p>Add a new administrator.</p>
{{ form(form) }}
{% endblock %}